import { Geist, Geist_Mono, Inter, Montserrat} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import NavHeader from "@/components/shared/NavHeader";
import Footer from "@/components/shared/Footer";
import { Toaster } from "react-hot-toast";
import SubscribePopup from "@/components/subscribePopup/SubscribePopup";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Load Montserrat font with desired weights
const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // You can specify the weights you need
});

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // You can specify the weights you need
});



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Maximum Savings App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${inter.variable} antialiased`}
      >
        <NavHeader />
        <Navbar montserrat={montserrat.className}/>
        <Toaster position="top-center" reverseOrder={false} />
        {children}
        <SubscribePopup/>
        <Footer/>
      </body>
    </html>
  );
}
